// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoUy8Vb22OyTvERP-EjiDnzmjUu3OhxfE',
    appId: '1:256561730:web:e8221ecc542856906893db',
    messagingSenderId: '256561730',
    projectId: 'musicpochita-205ac',
    authDomain: 'musicpochita-205ac.firebaseapp.com',
    storageBucket: 'musicpochita-205ac.firebasestorage.app',
    measurementId: 'G-34KJEJEDV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiTkw1zEaPMxy314gQ2Hze39RghH00N-U',
    appId: '1:256561730:android:60b37a07d015f0896893db',
    messagingSenderId: '256561730',
    projectId: 'musicpochita-205ac',
    storageBucket: 'musicpochita-205ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2GQUKFLSnbtEnWD6pzERCXs613qqsnrg',
    appId: '1:256561730:ios:2084edb607c9f07f6893db',
    messagingSenderId: '256561730',
    projectId: 'musicpochita-205ac',
    storageBucket: 'musicpochita-205ac.firebasestorage.app',
    iosClientId: '256561730-imsf8mbchrtf0m9mfnldbe6dqppmaumu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2GQUKFLSnbtEnWD6pzERCXs613qqsnrg',
    appId: '1:256561730:ios:2084edb607c9f07f6893db',
    messagingSenderId: '256561730',
    projectId: 'musicpochita-205ac',
    storageBucket: 'musicpochita-205ac.firebasestorage.app',
    iosClientId: '256561730-imsf8mbchrtf0m9mfnldbe6dqppmaumu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoUy8Vb22OyTvERP-EjiDnzmjUu3OhxfE',
    appId: '1:256561730:web:ec850970454f6f8a6893db',
    messagingSenderId: '256561730',
    projectId: 'musicpochita-205ac',
    authDomain: 'musicpochita-205ac.firebaseapp.com',
    storageBucket: 'musicpochita-205ac.firebasestorage.app',
    measurementId: 'G-MVL5V63YDC',
  );
}
